[package]
name = "sirup"
description = "CLI to spawn pre-authenticated IMAP/SMTP sessions and expose them via Unix sockets"
version = "0.1.0"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.87"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]
keywords = ["cli", "imap", "session", "smtp", "auth"]
homepage = "https://pimalaya.org"
repository = "https://github.com/pimalaya/sirup"

[features]
default = ["rustls-ring", "scram", "imap", "smtp"]
imap = ["dep:io-imap", "pimalaya-cli/imap"]
smtp = ["dep:io-smtp", "pimalaya-cli/smtp"]
scram = ["io-imap?/scram", "io-smtp?/scram"]
native-tls  = ["pimalaya-stream/native-tls", "io-pim-discovery/native-tls", "io-imap?/native-tls", "io-smtp?/native-tls"]
rustls-aws  = ["pimalaya-stream/rustls-aws", "io-pim-discovery/rustls-aws", "io-imap?/rustls-aws", "io-smtp?/rustls-aws"]
rustls-ring = ["pimalaya-stream/rustls-ring", "io-pim-discovery/rustls-ring", "io-imap?/rustls-ring", "io-smtp?/rustls-ring"]
vendored = ["pimalaya-stream/vendored", "io-imap?/vendored", "io-smtp?/vendored", "io-pim-discovery/vendored"]

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[build-dependencies]
pimalaya-cli = { version = "0.1", default-features = false, features = ["build"] }

[dependencies]
anyhow = "1"
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
dirs = "6"
io-imap = { version = "0.3", default-features = false, features = ["client"], optional = true }
io-pim-discovery = { version = "0.3", default-features = false, features = ["pacc", "autoconfig", "rfc6186", "client"] }
io-smtp = { version = "0.2", default-features = false, features = ["client"], optional = true }
log = "0.4"
pimalaya-cli = { version = "0.1", default-features = false, features = ["prompt", "spinner", "terminal", "wizard"] }
pimalaya-config = { version = "0.1", default-features = false, features = ["toml", "secret"] }
pimalaya-stream = { version = "0.1", default-features = false, features = ["std"] }
secrecy = { version = "0.10", default-features = false, features = ["serde"] }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
url = { version = "2.2", default-features = false, features = ["serde"] }

[target.'cfg(windows)'.dependencies]
uds_windows = "1"
