# Socket directory for all accounts, defaults to $XDG_RUNTIME_DIR
#socks-dir = "/run/user/1000"

[accounts.example]

# Socket file for this account, defaults to $XDG_RUNTIME_DIR/sirup/{account}.sock
#sock-file = "/run/user/1000/sirup/imap.sock"

# URL connection in form (imap|smtp)[s]://host[:port]
url = "imap://127.0.0.1"

# TLS provider
tls.provider = "rustls"
#tls.provider = "native-tls"

# Crypto provider for rustls
tls.rustls.crypto = "ring"
#tls.rustls.crypto = "aws"

# Custom TLS certificate
#tls.cert = "/path/to/custom/cert.pem"

# Enable STARTTLS (when URL scheme is imaps or smtps)
starttls = false

# SASL mechanisms to try in this particular order
sasl.mechanisms = ["plain", "login"]

# SASL ANONYMOUS
# https://datatracker.ietf.org/doc/html/rfc4505
sasl.anonymous.message = "himalaya"

# SASL PLAIN
# https://datatracker.ietf.org/doc/html/rfc4616
sasl.plain.authcid = "username"
sasl.plain.passwd.command = ["mimosa", "password", "read", "example"]
#sasl.plain.passwd.raw = "***"

# SASL LOGIN
# https://datatracker.ietf.org/doc/html/draft-murchison-sasl-login-00
sasl.login.username = "username"
sasl.login.password.command = ["mimosa", "password", "read", "example"]
#sasl.login.password.raw = "***"
