[sources]
allow-git = [
  "https://github.com/pimalaya/cli",
  "https://github.com/pimalaya/config",
  "https://github.com/pimalaya/io-discovery",
  "https://github.com/pimalaya/io-http",
  "https://github.com/pimalaya/io-imap",
  "https://github.com/pimalaya/io-smtp",
  "https://github.com/pimalaya/stream",
  "https://github.com/soywod/domain",
]
unknown-git = "deny"
unknown-registry = "deny"

[licenses]
allow = [
  "AGPL-3.0-only",
  "Apache-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]
